# Generated by Django 2.2.7 on 2020-06-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название команды')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('icon', models.ImageField(null=True, upload_to='team/logo/', verbose_name='Логотип команды')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('photo', models.ImageField(null=True, upload_to='team/member/', verbose_name='Фото')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='Номер')),
                ('amplua', models.CharField(max_length=255, null=True, verbose_name='Амплуа')),
                ('birthday', models.CharField(max_length=255, null=True, verbose_name='День рождения')),
                ('nationality', models.CharField(max_length=255, null=True, verbose_name='Гражданство')),
                ('height', models.CharField(max_length=255, null=True, verbose_name='Рост')),
                ('weight', models.CharField(max_length=255, null=True, verbose_name='Вес')),
                ('start_play', models.CharField(max_length=255, null=True, verbose_name='Перешел')),
                ('info', models.TextField(null=True, verbose_name='Описание')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='В составе')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
