# Generated by Django 2.2.7 on 2020-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='amplua',
            field=models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('SD', 'Полузащитник'), ('AT', 'Нападающий')], default='GK', max_length=2, verbose_name='Амплуа'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='birthday',
            field=models.DateField(max_length=255, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='start_play',
            field=models.DateField(max_length=255, null=True, verbose_name='Перешел'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
    ]
