# Generated by Django 2.1.4 on 2020-06-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0002_match_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='Цена билета')),
                ('match', models.ManyToManyField(to='match.Match', verbose_name='Матч')),
                ('place', models.ManyToManyField(to='stadium.Place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Цена билета',
                'verbose_name_plural': 'Цены билетов',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Номер ряда')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название сектора')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сектора',
            },
        ),
        migrations.AddField(
            model_name='row',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.Sector', verbose_name='Относится к'),
        ),
        migrations.AddField(
            model_name='place',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.Row', verbose_name='Относится к'),
        ),
    ]
