# Generated by Django 2.2.7 on 2020-06-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_is_active'),
        ('stadium', '0002_auto_20200615_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='match',
        ),
        migrations.AddField(
            model_name='price',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Match', verbose_name='Матч'),
        ),
        migrations.RemoveField(
            model_name='price',
            name='place',
        ),
        migrations.AddField(
            model_name='price',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.Place', verbose_name='Место'),
        ),
    ]
