# Generated by Django 2.2.7 on 2020-06-15 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('author', models.CharField(default='Пресс-служба ФК Ростов', max_length=255, null=True, verbose_name='Автор')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='blog/', verbose_name='Изображение (285 x 150)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Статья')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
            },
        ),
    ]
