# Generated by Django 2.2.7 on 2020-06-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('ligue', models.CharField(default='Премьер Лига', max_length=255, verbose_name='Лига')),
                ('place', models.CharField(default='Арена Ростов', max_length=255, verbose_name='Место')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='team.Team', verbose_name='Команда1')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='team.Team', verbose_name='Команда2')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
