# Generated by Django 2.2.7 on 2020-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_preorder',
            field=models.BooleanField(null=True, verbose_name='Только предзаказ ?'),
        ),
    ]
